#!/bin/bash

. /unixworks/bl_tools/etc/bl_tools.sh
. /unixworks/bl_tools/etc/promotion.sh

bl_conf_auto "BL_ENG_PROFILE" "$BL_ENG_PROFILE"

cat /unixworks/bl_tools/etc/headerlist.txt | while read DEPOT_HEADER
do
    HEADER="$(echo $DEPOT_HEADER | sed -e "s#$BL_ENG_BASE/##")"
    LOCAL_HEADER="$BL_LOCAL_ENG/$HEADER"
    LOCAL_DIR=$(dirname "$LOCAL_HEADER")
    echo RUNNING: bl_getDepotFile --depotfile "$DEPOT_HEADER" --dstdir "$LOCAL_DIR"
    bl_getDepotFile --depotfile "$DEPOT_HEADER" --dstdir "$LOCAL_DIR"
done
